title: NewPath Docs
description: Öffentliche Dokumentation für NewPath – Echoes of the Wild

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://newpathmc.github.io"
baseurl: "/NewPath-Docs"

aux_links:
  "NewPath auf GitHub":
    - "https://github.com/NewPathMC/NewPath-Docs"

color_scheme: dark

enable_copy_code_button: true

search_enabled: true

back_to_top: true
back_to_top_text: "Zurück nach oben"

footer_content: "NewPath – Echoes of the Wild"