title: NewPath EOTW
description: Öffentliche Dokumentation für NewPath – Echoes of the Wild

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://newpathmc.github.io"
baseurl: "/NewPath-Docs"

aux_links:
  "Discord beitreten": "https://discord.gg/DEIN-CODE"

aux_links_new_tab: true

color_scheme: newpath

enable_copy_code_button: true

search_enabled: true

back_to_top: true
back_to_top_text: "Zurück nach oben"

footer_content: "NewPath – Echoes of the Wild"
last_edit_timestamp: false
gh_edit_link: false